### ISSUE TITLE
前端（fe）运行地址为 https://web.0351zhuangxiu.com:443/ ，页面不是你展示的页面。

### ISSUE THREAD

**Issue by OFreshman** [zymfe/VueNode#11]
前端（fe）运行地址为 https://web.0351zhuangxiu.com:443/ ，页面不是你展示的那个页面。

**Comment by OFreshman** [comment]
> 前端（fe）运行地址为 https://web.0351zhuangxiu.com:443/ ，页面不是你展示的那个页面。

把 build/wbpack.dev.config.js 里 host 改为空字符串即可
```js
config.devServer = {
    host: '',
   //....
  };
```

**Comment by zhaoyiming0803** [comment]
> > 前端（fe）运行地址为 https://web.0351zhuangxiu.com:443/ ，页面不是你展示的那个页面。
> 
> 把 build/wbpack.dev.config.js 里 host 改为空字符串即可
> 
> ```js
> config.devServer = {
>     host: '',
>    //....
>   };
> ```

本地默认启动的是https的node服务，需要配置你本地host为：web.0351zhuangxiu.com 127.0.0.1
