### ISSUE TITLE
关于数据库连接的问题

### ISSUE THREAD

**Issue by WildLight** [zymfe/VueNode#14]
老哥你这个数据库连接上好像没有释放连接的代码呀，这样不会出错么

**Comment by zhaoyiming0803** [comment]
> 老哥你这个数据库连接上好像没有释放连接的代码呀，这样不会出错么

没太明白什么意思

**Comment by chen512** [comment]
老哥，链接数据库报： Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by chen512** [comment]
解决了。
