### ISSUE TITLE
yarn start 报错

### ISSUE THREAD

**Issue by zhaixww** [zymfe/VueNode#8]
#
![11](https://user-images.githubusercontent.com/22145325/85257970-404cea80-b499-11ea-8e77-49c416fef193.jpg)

**Comment by zhaixww** [comment]
![11](https://user-images.githubusercontent.com/22145325/85270685-46989200-b4ac-11ea-8111-7acc99ed7179.jpg)

**Comment by zhaixww** [comment]
作者你好，代码clone到本地安装各个依赖后，就执行yarn start 和yarn dev吗，我yarn start启动server报错了 ，tour.sql也导了

**Comment by zhaoyiming0803** [comment]
> 作者你好，代码clone到本地安装各个依赖后，就执行yarn start 和yarn dev吗，我yarn start启动server报错了 ，tour.sql也导了

显示：express listen port 8091，说明 node 正常启动了，但是报错 Access denied for user ......，检查下你数据库是否启动并且正确导入了 tour.sql。
